.gitignore
README.md
docs/pull_request_template.md

[DSND-2255](https://companieshouse.atlassian.net/browse/DSND-2255)
[DSND-2255]: https://companieshouse.atlassian.net/browse/DSND-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2255: Update README, .gitignore and add PR template

---

terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/variables.tf

* made healthcheck endpoint same as api after talking to Billy]
* made api_local_url a secret
[DSND-2302](https://companieshouse.atlassian.net/browse/DSND-2302)
- [Y] Is the PR as small as it can be?
- [Y] Has the Jira ticket been updated with any relevant comments?
- [Y] Is the `README` up to date?
- [Y] Has the `POM` been updated for the latest versions of dependencies?
- [Y] Has the code been double-checked against `main`?
- [Y] Does the code adhere standards in this repository, including SonarQube checks?
- [Y ] Do the code changes have unit and integration tests with code coverage > 80%?
None
[DSND-2302]: https://companieshouse.atlassian.net/browse/DSND-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

DSND-2302: Correct terraform config

---

terraform/groups/ecs-service/main.tf

DSND-2119: Update terraform modules version and path

---

pom.xml
src/main/java/uk/gov/companieshouse/filinghistory/consumer/delta/DeltaConfig.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/kafka/KafkaConfig.java
suppress.xml
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/variables.tf

DSND-2119: Remove unnecessary terraform and update SDK manager Java version

---

terraform/groups/ecs-service/data.tf
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf

DSND-2119: Add load balancer terraform config

---

pom.xml

DSND-2119: Add maven execution goal to fix failing build

---

src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/filinghistory/consumer/FilingHistoryApplicationIT.java
terraform/groups/ecs-service/locals.tf

DSND-2119: Specify expected healthcheck response

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/logging/LoggingKafkaListenerAspect.java

DSND-2119: Add structured logging consumer aspect

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/functions/SentenceCase.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/functions/LowerCaseTest.java

Just a small PR to try fix some test cases and improve the possessiveness class. 
[DSND-2339](https://companieshouse.atlassian.net/browse/DSND-2339)
[DSND-2339]: https://companieshouse.atlassian.net/browse/DSND-2339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2339: Fix LowerCaseTest and improve possessiveness.

---

pom.xml

Moved the dependencies to be exclusions rather than specific imports
[DSND-2385](https://companieshouse.atlassian.net/browse/DSND-2385)
[DSND-2385]: https://companieshouse.atlassian.net/browse/DSND-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2385: POM updates and exclusions

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/TransformerConfig.java

Fix transform rules class path resource

---

pom.xml
src/main/java/uk/gov/companieshouse/filinghistory/consumer/delta/PreTransformMapper.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/TransformerConfig.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/functions/FormatDate.java
src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/DescriptionValuesMapperTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/InternalFilingHistoryApiMapperTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/OriginalValuesMapperTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/PreTransformMapperTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/TransformerTestingUtils.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/functions/CapitalCaptorTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/delta/transformrules/functions/ProcessCapitalTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PutRequestMatcher.java
src/test/resources/TM01_request_body.json

* Format receive_date field before transform
* Refactor use of object mappers in tests
* Refactor integration test to use wiremock
[DSND-2403](https://companieshouse.atlassian.net/browse/DSND-2403)
[DSND-2403]: https://companieshouse.atlassian.net/browse/DSND-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2403: Implement Wiremock integration test

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClient.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/ResponseHandler.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/kafka/Consumer.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/kafka/InvalidMessageRouter.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/logging/LoggingKafkaListenerAspect.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/serdes/CapitalDeserialiser.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/serdes/ChsDeltaDeserialiser.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/serdes/ChsDeltaSerialiser.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/serdes/FilingHistoryDeltaDeserialiser.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClientTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/ResponseHandlerTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PutRequestMatcher.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/serdes/ChsDeltaDeserialiserTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/serdes/FilingHistoryDeltaDeserialiserTest.java

* upgrade it to error level log message
* remove newline characters
[DSND-2278](https://companieshouse.atlassian.net/browse/DSND-2278)
[DSND-2278]: https://companieshouse.atlassian.net/browse/DSND-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2278: Fix invalid topic message.

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/SentenceCase.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/TitleCase.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/TransformerServiceTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatDateTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/SentenceCaseTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/TitleCaseTest.java
src/test/resources/data/SH07_request_body.json
src/test/resources/data/TM01_request_body.json

* Sentence case and title case functions have been made to follow the Perl as closely as possible.
[DSND-2376](https://companieshouse.atlassian.net/browse/DSND-2376)
[DSND-2376]: https://companieshouse.atlassian.net/browse/DSND-2376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2376: Fix sentence and title case functions

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars

[DSND-2436](https://companieshouse.atlassian.net/browse/DSND-2436)
[DSND-2436]: https://companieshouse.atlassian.net/browse/DSND-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2436: Change set env files to true for staging and live

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/CapitalCaptor.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/TransformerTestingUtils.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/CapitalCaptorTest.java
src/test/resources/data/capital/SH03_delta.json
src/test/resources/data/capital/SH03_request_body.json

* Fixes a bug where capital date was not being formatted before being sent to the API.
[DSND-2464](https://companieshouse.atlassian.net/browse/DSND-2464)
[DSND-2464]: https://companieshouse.atlassian.net/browse/DSND-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2464: Fix capital date format when treasury description

---

src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/resources/data/accounts/AAMD_rule_12_delta.json
src/test/resources/data/accounts/AAMD_rule_12_request_body.json
src/test/resources/data/accounts/AAMD_rule_1_delta.json
src/test/resources/data/accounts/AAMD_rule_1_request_body.json
src/test/resources/data/accounts/AAMD_rule_7_delta.json
src/test/resources/data/accounts/AAMD_rule_7_request_body.json
src/test/resources/data/accounts/AAMD_rule_9_delta.json
src/test/resources/data/accounts/AAMD_rule_9_request_body.json
src/test/resources/data/accounts/AA_rule_10_delta.json
src/test/resources/data/accounts/AA_rule_10_request_body.json
src/test/resources/data/accounts/AA_rule_12_delta.json
src/test/resources/data/accounts/AA_rule_12_request_body.json
src/test/resources/data/accounts/AA_rule_14_delta.json
src/test/resources/data/accounts/AA_rule_14_request_body.json
src/test/resources/data/accounts/AA_rule_20_delta.json
src/test/resources/data/accounts/AA_rule_20_request_body.json
src/test/resources/data/accounts/AA_rule_23_delta.json
src/test/resources/data/accounts/AA_rule_23_request_body.json
src/test/resources/data/accounts/AA_rule_25_delta.json
src/test/resources/data/accounts/AA_rule_25_request_body.json
src/test/resources/data/accounts/AA_rule_26_delta.json
src/test/resources/data/accounts/AA_rule_26_request_body.json
src/test/resources/data/accounts/AA_rule_6_delta.json
src/test/resources/data/accounts/AA_rule_6_request_body.json
src/test/resources/data/accounts/AA_rule_8_delta.json
src/test/resources/data/accounts/AA_rule_8_request_body.json
src/test/resources/data/accounts/AA_rule_9_delta.json
src/test/resources/data/accounts/AA_rule_9_request_body.json

Adding integration tests for accounts category filing history deltas.
[DSND-2463](https://companieshouse.atlassian.net/browse/DSND-2463)
[DSND-2463]: https://companieshouse.atlassian.net/browse/DSND-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2463: Add 13 Comprehensive ITests

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/serdes/ChsDeltaDeserialiser.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatDate.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationDataGenerator.java
src/test/resources/data/officers/EW01RSS_delta.json
src/test/resources/data/officers/EW01RSS_request_body.json

* IntegrationDataGenerator now looks for generated Perl FH documents by various methods while building test data sets
* Added extra logging for errors when transforming deltas
* Added extra test data
[DSND-2453](https://companieshouse.atlassian.net/browse/DSND-2453)
Bug tickets raised
[DSND-2500](https://companieshouse.atlassian.net/browse/DSND-2500)
[DSND-2501](https://companieshouse.atlassian.net/browse/DSND-2501)
[DSND-2502](https://companieshouse.atlassian.net/browse/DSND-2502)
[DSND-2503](https://companieshouse.atlassian.net/browse/DSND-2503)
[DSND-2508](https://companieshouse.atlassian.net/browse/DSND-2508)
[DSND-2507](https://companieshouse.atlassian.net/browse/DSND-2507)
_Add any testing hints or …

DSND-2453: Fixes or some bugs found during bulk integration tests

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/PreTransformMapper.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/PreTransformMapperTest.java
src/test/resources/data/address/287_delta.json
src/test/resources/data/address/287_request_body.json

* Apply new transformation logic within the PreTransformMapper
* Add new 287 test case to ConsumerPositiveComprehensiveIT
[DSND-2502](https://companieshouse.atlassian.net/browse/DSND-2502)
New test case address/287 added to integration tests.
For manual test- can post the delta request found in PR.
[DSND-2502]: https://companieshouse.atlassian.net/browse/DSND-2502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2502 Fix description mapping when it contains angled brackets

---

pom.xml

[DSND-2138](https://companieshouse.atlassian.net/browse/DSND-2138)
[DSND-2138]: https://companieshouse.atlassian.net/browse/DSND-2138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2138: Update sdk version in pom

---

src/main/resources/transform_rules.yml

* Replicates changes made to chs-backend filing-history-description-mappings.yaml since first cloned.
* Changes include amending the description for an AM08 and making PRE87 rules more general.
[DSND-2517](https://companieshouse.atlassian.net/browse/DSND-2517)
[DSND-2517]: https://companieshouse.atlassian.net/browse/DSND-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2517: Bring in changes to transform rules in chs-backend

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/DescriptionValuesMapper.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/ResolutionNodeMapper.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/TransactionKindService.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerInvalidPayloadExceptionIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerNonRetryableExceptionIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerRetryableExceptionIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/DescriptionValuesMapperTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/ResolutionNodeMapperTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/TransactionKindServiceTest.java
src/test/resources/data/resolution/RES15_child_delta.json
src/test/resources/data/resolution/RES15_child_request_body.json
src/test/resources/data/resolution/RES15_top_level_delta.json
src/test/resources/data/resolution/RES15_top_level_request_body.json

* Implements handling of RES15 form types.
* Also handles cases where description values may be persisted as empty.
[DSND-2433](https://companieshouse.atlassian.net/browse/DSND-2433)
[DSND-2433]: https://companieshouse.atlassian.net/browse/DSND-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2433: Transform RES15s

---

pom.xml

This PR updates the pom in preparation for the main ticket.
[DSND-2508](https://companieshouse.atlassian.net/browse/DSND-2508)
[DSND-2508]: https://companieshouse.atlassian.net/browse/DSND-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2508: Update versions in pom

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/CapitalCaptor.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/CapitalCaptorTest.java
src/test/resources/data/capital/SH05_delta.json
src/test/resources/data/capital/SH05_request_body.json

This PR implements the fix for the capital date bug where the `date` field was not being added to the `ObjectNode` and therefore not sent in the PUT request body.
[DSND-2508](https://companieshouse.atlassian.net/browse/DSND-2508)
[DSND-2508]: https://companieshouse.atlassian.net/browse/DSND-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2508: Fix missing capital date bug

---

pom.xml
src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/InternalFilingHistoryApiMapper.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/InternalFilingHistoryApiMapperTest.java
src/test/resources/data/annotation/annotation_request_body.json
src/test/resources/data/annotation/top_level_annotation_delta.json
src/test/resources/data/annotation/top_level_annotation_request_body.json

[DSND-2372](https://companieshouse.atlassian.net/browse/DSND-2372)
[DSND-2372]: https://companieshouse.atlassian.net/browse/DSND-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2372: Transform top level annotation to api request

---

src/main/resources/transform_rules.yml
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/resources/data/officers/RP04LLPSC04_delta.json
src/test/resources/data/officers/RP04LLPSC04_request_body.json
src/test/resources/data/officers/RP04LLPSC05_delta.json
src/test/resources/data/officers/RP04LLPSC05_request_body.json
src/test/resources/data/officers/RP04PSC03_delta.json
src/test/resources/data/officers/RP04PSC03_request_body.json
src/test/resources/data/officers/RP04PSC07_delta.json
src/test/resources/data/officers/RP04PSC07_request_body.json
src/test/resources/data/officers/RP04PSC09_delta.json
src/test/resources/data/officers/RP04PSC09_request_body.json

* All buggy RP04 form types fixed.
* Tests added to ConsumerPositiveComprehensiveIT
[DSND-2500](https://companieshouse.atlassian.net/browse/DSND-2500)
[DSND-2500]: https://companieshouse.atlassian.net/browse/DSND-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2500: Fix transform_rules.yml for PSC form types.

---

src/test/resources/data/officers/RP04LLPSC04_request_body.json
src/test/resources/data/officers/RP04LLPSC05_request_body.json
src/test/resources/data/officers/RP04PSC07_request_body.json

[DSND-2600](https://companieshouse.atlassian.net/browse/DSND-2600)
[DSND-2600]: https://companieshouse.atlassian.net/browse/DSND-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2600: Fix expected test data

---

src/main/resources/transform_rules.yml
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/resources/data/change-of-name/CONDIR_delta.json
src/test/resources/data/change-of-name/CONDIR_request_body.json

* Adds a transformation rule to support CONDIR child transactions.
* The previous other CONDIR rule supports top level and is left in just in case it is possible to get a top level CONDIR though its not likely.
[DSND-2606](https://companieshouse.atlassian.net/browse/DSND-2606)
[DSND-2606]: https://companieshouse.atlassian.net/browse/DSND-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2605: Add child CONDIR transform rule

---

src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkIntegrationTestUtils.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkMappingDescriptionIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/E2EGetResponseIntegrationIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationDescriptionGenerator.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationGETResponseGenerator.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PutRequestDescriptionMatcher.java

* Added a new table, fh_staging_deltas, that holds deltas generated from Staging.
* Updated the test data generator to use deltas from the fh_staging_deltas table.
* Refactored PutRequestDescriptionMatcher to match descriptions from the annotations, associated_filings and resolutions arrays rather than just the top-level description.
[DSND-2680](https://companieshouse.atlassian.net/browse/DSND-2680)
[DSND-2680]: https://companieshouse.atlassian.net/browse/DSND-2680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2680: Refactor bulk test for comparing description values

---

pom.xml
src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClient.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClientTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkIntegrationTestUtils.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkMappingDescriptionIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java

* Remove FH endpoint prefixes
[DSND-2692](https://companieshouse.atlassian.net/browse/DSND-2692)
[DSND-2692]: https://companieshouse.atlassian.net/browse/DSND-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2692: Remove FH endpoint prefixes

---

src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/E2EGetResponseIntegrationIT.java

* Error reports use the raw JSON returned by the API calls
* Fixed the logic around mismatched `action_date` types
* Simplified node lookups by using JSON pointers
[DSND-2691](https://companieshouse.atlassian.net/browse/DSND-2691)
[DSND-2691]: https://companieshouse.atlassian.net/browse/DSND-2691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2691: Refactored E2EGetResponseIntegrationIT to simplify the field masking

---

src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/E2EGetResponseIntegrationIT.java

Clean up and simplify the masking logic of `E2EGetResponseIntegrationIT.shouldMatchGetResponsesFromPerlEndpoints`

No-Ticket: E2E test tidy up

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Override default required CPUs

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Up memory to valid value with CPU config

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Up required vCPUs to 1

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Up vCPU to 2

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Remove CPU and memory overwrite

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Up scale in cooldown

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars

DSND-2743: Up CPU to .5

---

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars

DSND-2743: Up CPU and scale in cooldown to quicken live-apply

---

src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatNumber.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatNumberTest.java

* Now replicates exactly what the perl does so there are no unexpected differences.
[DSND-2737](https://companieshouse.atlassian.net/browse/DSND-2737)
[DSND-2737]: https://companieshouse.atlassian.net/browse/DSND-2737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2737: Refactor format number transformer function

---

README.md
src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/ResponseHandler.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/ResponseHandlerTest.java

* Change logic so that all exceptions are retryable besides 400 and 409
* Update README.md accordingly
[DSND-2951](https://companieshouse.atlassian.net/browse/DSND-2951)
[DSND-2951]: https://companieshouse.atlassian.net/browse/DSND-2951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2951: Modify exceptions handling

---

pom.xml
src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/ResponseHandler.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/kafka/Consumer.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/kafka/InvalidMessageRouter.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/logging/LoggingKafkaListenerAspect.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/LinksMapper.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/FilingHistoryDeltaProcessor.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/TransactionKindService.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/TransformerService.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatDate.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/FilingHistoryDeltaProcessorTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/TransformerServiceTest.java

This PR primarily adds entity id to the log map at the start of the delta process so this field can be tracked more easily, by FESS, back to CHIPS.
Other changes also made to simplify log messages.
[DSND-2872](https://companieshouse.atlassian.net/browse/DSND-2872)
[DSND-2872]: https://companieshouse.atlassian.net/browse/DSND-2872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2872: Update structured logging

---

pom.xml
src/test/resources/data/delete-delta.json

This PR updates the tests to ensure the consumer can handle a delta_at field on an incoming delete delta.
[DSND-3109](https://companieshouse.atlassian.net/browse/DSND-3109)
[DSND-3109]: https://companieshouse.atlassian.net/browse/DSND-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3109: Add delta at to delete delta tests

---

pom.xml
src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClient.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteApiClientRequest.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaService.java
src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/TransactionKindService.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClientTest.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java
src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaServiceTest.java

* Refactor DeleteDeltaService to get encoded transaction ID
* Update tests
* WIP pom.xml to get correct version
[DSND-3112](https://companieshouse.atlassian.net/browse/DSND-3112)
[DSND-3112]: https://companieshouse.atlassian.net/browse/DSND-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3122 Add deltaAt and entityId into API delete call

---

Makefile
pom.xml
src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/filinghistory/consumer/FilingHistoryApplicationIT.java
suppress.xml
terraform/groups/ecs-service/locals.tf

[DSND-3241](https://companieshouse.atlassian.net/browse/DSND-3241)
[DSND-3241]: https://companieshouse.atlassian.net/browse/DSND-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3241: Update dependency check and healthcheck
