README.md, src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/ResponseHandler.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/OriginalValuesMapper.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/OriginalValuesMapperTest.java, src/test/resources/data/mortgage/MR02_rule_3_delta.json, src/test/resources/data/mortgage/MR02_rule_3_request_body.json
* Original values fields were being transformed once by YAML and once post YAML, have removed the second time post YAML.
* MR02 integration test confirms fix is working as intended.
* Updated README with proper docker build command.
[DSND-2405](https://companieshouse.atlassian.net/browse/DSND-2405)
[DSND-2405]: https://companieshouse.atlassian.net/browse/DSND-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2405: Fixes bug where original_values dates were transformed twice

README.md, pom.xml, src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatDate.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/FormatDateTest.java, src/test/resources/data/capital/EW05RSS_delta.json, src/test/resources/data/capital/EW05RSS_request_body.json
* Added a check to see if the source text is already correctly formatted
* Updated the integration tests to include an example where double transformation could occur
* Added a guard to stop bulk integration tests being run in normal builds
* Updated the readme to add details of the environment variable, `RUN_BULK_TEST` used to guard the bulk tests
* Updated POM to use Spring Boot 3.2.4
[DSND-2503](https://companieshouse.atlassian.net/browse/DSND-2503)
[DSND-2503]: https://companieshouse.atlassian.net/browse/DSND-2503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2503: Stop FormatDate.format() being called twice and failing on the 2nd pass

pom.xml, src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/AnnotationTransformer.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/TransformerFactory.java, src/main/resources/transform_rules.yml, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/TransformerTestingUtils.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/AnnotationTransformerTest.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/transformrules/functions/TransformerFactoryTest.java, src/test/resources/data/annotation/annotation_request_body.json
This PR fixes a bug where the description and category fields on the child object were being set to the incorrect value during transformation.
[DSND-2515](https://companieshouse.atlassian.net/browse/DSND-2515)
[DSND-2515]: https://companieshouse.atlassian.net/browse/DSND-2515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2515: Fix annotation transformation where substitution is treated as field name

README.md, src/main/resources/transform_rules.yml, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/resources/data/mortgage/LLP466(Scot)_delta.json, src/test/resources/data/mortgage/LLP466(Scot)_request_body.json
Added chargeCreationDate handling for form type LLP466(Scot) within the transform rule and a test case to make sure it works. 
[DSND-2534](https://companieshouse.atlassian.net/browse/DSND-2534)
[DSND-2534]: https://companieshouse.atlassian.net/browse/DSND-2534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2534: Updated existing transform rule and test case to make sure works.

src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/TransactionKindService.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/TransactionKindServiceTest.java, src/test/resources/data/resolution/RES01_no_barcode_delta.json, src/test/resources/data/resolution/RES01_no_barcode_request_body.json
* Resolutions, other than RES15s, without a barcode were incorrectly being sent as top level transactions to the data API.
* This has been fixed by checking for resolution type first then deciding how to encode the ID.
[DSND-2363](https://companieshouse.atlassian.net/browse/DSND-2363)
[DSND-2363]: https://companieshouse.atlassian.net/browse/DSND-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2363: Implement transaction kind handling for resolutions without a barcode

README.md, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationDataGenerator.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PutRequestMatcher.java
* Perl-generated Mongo documents are now deleted after generation to fix the issue of not being found during PUT request generation.
* The Local/Tilt Mongo filing history collection is cleared prior to starting the test run.
* In `PutRequestMatcher`, remove body matching on transaction kind when value is null in the expected document
* `document_id` now populated correctly for resolutions.
* Environment variable `PERL_SALT` changed to `TRANSACTION_ID_SALT`
[DSND-2579](https://companieshouse.atlassian.net/browse/DSND-2578)
[DSND-2579]: https://companieshouse.atlassian.net/browse/DSND-2579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> DSND-2579: Fix expected test data empty values

README.md
Updated README to add  `kafka.polling_duration` can be set locally to speed up integration tests
[DSND-2578](https://companieshouse.atlassian.net/browse/DSND-2578)
[DSND-2578]: https://companieshouse.atlassian.net/browse/DSND-2578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND2578: Updated README with config for Kafka poling times in tests

README.md, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkMappingDescriptionIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationDataGenerator.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationDescriptionGenerator.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/KafkaUtils.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PutRequestDescriptionMatcher.java
* Added `BulkMappingDescriptionIT` to check transformations that cannot be performed in
`ConsumerPositiveComprehensiveIT` due to issues with the Perl code
* Matches on the expected descriptions values from 2024-01-17-data-sync-test-data-v2.xlsx
* Refactored the Kafka polling timeout to use the environment variable `KAFKA_POLLING_DURATION`
and put the duration calculation in `KafkaUtils`
* Excluded deltas that are known to fail in Perl in integration tests
* Reformatted queries
[DSND-2611](https://companieshouse.atlassian.net/browse/DSND-2611)
[DSND-2611]: https://companieshouse.atlassian.net/browse/DSND-2611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
=> DSND2578: Added a bulk integration test for deltas that fail in Perl

README.md, src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClient.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaService.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClientTest.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaServiceTest.java, src/test/resources/data/officers/RP04LLPSC04_request_body.json, src/test/resources/data/officers/RP04LLPSC05_request_body.json, src/test/resources/data/officers/RP04PSC07_request_body.json
This PR changes the delete process to use the raw entity_id of a delta rather than the encoded entity_id. This change is due to a decision made for the logic in the API where we delete by entity_id rather than transaction_id.
[DSND-2600](https://companieshouse.atlassian.net/browse/DSND-2600)
[DSND-2600]: https://companieshouse.atlassian.net/browse/DSND-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2600: Delete FH Transaction using Entity ID

README.md, pom.xml, src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClient.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaService.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClientTest.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaServiceTest.java, src/test/resources/data/officers/RP04LLPSC04_request_body.json, src/test/resources/data/officers/RP04LLPSC05_request_body.json, src/test/resources/data/officers/RP04PSC07_request_body.json
This PR changes the delete process to use the raw entity_id of a delta rather than the encoded entity_id. This change is due to a decision made for the logic in the API where we delete by entity_id rather than transaction_id.
Update dependencies in Pom.
Fix incorrect expected test data.
[DSND-2600](https://companieshouse.atlassian.net/browse/DSND-2600)
[DSND-2600]: https://companieshouse.atlassian.net/browse/DSND-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2600: Change delete process to use entity_id rather than transaction_id

src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/DescriptionValuesMapper.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/JsonNodeCleaner.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/DescriptionValuesMapperTest.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/posttransform/JsonNodeCleanerTest.java, src/test/resources/data/mortgage/402R(NI)_delta.json, src/test/resources/data/mortgage/402R(NI)_request_body.json
* Previously, description_values would be sent in the request body as an object with all it's fields being null or empty strings.
* This fix now makes it so any description_values objects that have no populated fields (i.e., not null or empty), will be set to null in the mapping process, and so not sent in the request body to the API.
[DSND-2613](https://companieshouse.atlassian.net/browse/DSND-2613)
[DSND-2613]: https://companieshouse.atlassian.net/browse/DSND-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2613: Fix bug where empty objects were being sent in request

src/main/resources/transform_rules.yml, src/test/resources/data/mortgage/LLP466(Scot)_request_body.json, src/test/resources/data/mortgage/MR02_rule_3_request_body.json
* Stops transformation of charge_creation_date and property_acquired_date original values.
[DSND-2657](https://companieshouse.atlassian.net/browse/DSND-2657)
[DSND-2657]: https://companieshouse.atlassian.net/browse/DSND-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2657: Do not transform original_values

src/main/resources/transform_rules.yml, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/resources/data/officers/RP04LLPSC01_delta.json, src/test/resources/data/officers/RP04LLPSC01_request_body.json, src/test/resources/data/officers/RP04LLPSC02_delta.json, src/test/resources/data/officers/RP04LLPSC02_request_body.json, src/test/resources/data/officers/RP04LLPSC03_delta.json, src/test/resources/data/officers/RP04LLPSC03_request_body.json, src/test/resources/data/officers/RP04LLPSC07_delta.json, src/test/resources/data/officers/RP04LLPSC07_request_body.json, src/test/resources/data/officers/RP04PSC01_delta.json, src/test/resources/data/officers/RP04PSC01_request_body.json, src/test/resources/data/officers/RP04PSC02_delta.json, src/test/resources/data/officers/RP04PSC02_request_body.json, src/test/resources/data/officers/RP04PSC04_delta.json, src/test/resources/data/officers/RP04PSC04_request_body.json, src/test/resources/data/officers/RP04PSC05_delta.json, src/test/resources/data/officers/RP04PSC05_request_body.json, src/test/resources/data/officers/RP04SLPPSC04_delta.json, src/test/resources/data/officers/RP04SLPPSC04_request_body.json, src/test/resources/data/officers/RP04SLPPSC05_delta.json, src/test/resources/data/officers/RP04SLPPSC05_request_body.json, src/test/resources/data/officers/RP04SQPPSC04_delta.json, src/test/resources/data/officers/RP04SQPPSC04_request_body.json
This PR fixes a group of failing RP04xs that fail due to missing dates on the delta.
There are three failing scenarios which have been commented out and will be handled in a separate bug ticket. These would have needed the same fix as this PR, hence why they have been kept to avoid removing and then re-adding the work.
[DSND-2614](https://companieshouse.atlassian.net/browse/DSND-2614)
[DSND-2614]: https://companieshouse.atlassian.net/browse/DSND-2614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2614: Fix failing rp04s due to missing dates

src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkIntegrationTestUtils.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/E2EGetResponseIntegrationIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/IntegrationGETResponseGenerator.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PerlDocumentExtractor.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/PerlDocuments.java
The Bulk E2E tests need the GET responses from the Perl endpoints to compare with the output of the Java ones.
* Capture Perl GET responses using deltas from Staging
* Import these to a Kermit table `capdevjco2.bulk_testing_perl_docs`
* Update bulk test queries to source test data from the new table
* Update the Java API URIs to remove the `filing-history-data-api` prefix
* Added a utility class to harvest the Perl GET responses if the data table needs refreshing
[DSND-2692](https://companieshouse.atlassian.net/browse/DSND-2692)
[DSND-2692]: https://companieshouse.atlassian.net/browse/DSND-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> DSND-2692: Harvest Perl GET responses

src/main/resources/transform_rules.yml, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/resources/data/officers/RP04SLPPSC04_delta.json, src/test/resources/data/officers/RP04SLPPSC04_no_description_values_delta.json, src/test/resources/data/officers/RP04SLPPSC04_no_description_values_request_body.json, src/test/resources/data/officers/RP04SLPPSC04_request_body.json, src/test/resources/data/officers/RP04SLPPSC05_delta.json, src/test/resources/data/officers/RP04SLPPSC05_no_description_values_delta.json, src/test/resources/data/officers/RP04SLPPSC05_no_description_values_request_body.json, src/test/resources/data/officers/RP04SLPPSC05_request_body.json, src/test/resources/data/officers/RP04SQPPSC04_delta.json, src/test/resources/data/officers/RP04SQPPSC04_no_description_values_delta.json, src/test/resources/data/officers/RP04SQPPSC04_no_description_values_request_body.json, src/test/resources/data/officers/RP04SQPPSC04_request_body.json
* This is linked to DSND-2614 & DSND-2688.
* Due to dodgy data, we couldn't find examples of the description_values object existing on the delta from CHIPS. However, we have been told to handle both scenarios (where desc values does and does not exist) similarly to DSND-2688.
[DSND-2679](https://companieshouse.atlassian.net/browse/DSND-2679)
[DSND-2679]: https://companieshouse.atlassian.net/browse/DSND-2679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2679: Fix failing RP04s

src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/BulkIntegrationTestUtils.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/E2EGetResponseIntegrationIT.java
Updates to E2EGetResponseIntegrationIT include:
* Fixed some cases where the Java and Perl document ordering was mixed up
* Added a masking function to ignore description values where the rules have changed
[DSND-2689](https://companieshouse.atlassian.net/browse/DSND-2689)
[DSND-2689]: https://companieshouse.atlassian.net/browse/DSND-2689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2689: Mask known description differences in E2EGetResponseIntegationIT

pom.xml, src/main/resources/transform_rules.yml, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/resources/data/resolution/RES_delta.json, src/test/resources/data/resolution/RES_request_body.json
- Added a new transform rule for RES deltas
- Updated `ConsumerPositiveComprehensiveIT` with test data for a RES delta
- Excluded `com.nimbusds:nimbus-jose-jwt` that was a transitive dependency of `uk.gov.companieshouse:sdk-manager-java`
[DSND-2822](https://companieshouse.atlassian.net/browse/DSND-2822)
[DSND-2822]: https://companieshouse.atlassian.net/browse/DSND-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2822: Fixed transform rules for RES deltas

pom.xml, src/main/java/uk/gov/companieshouse/filinghistory/consumer/kafka/Consumer.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/logging/LoggingKafkaListenerAspect.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/logging/LoggingKafkaListenerAspectTest.java, src/test/resources/data/delete-delta.json
This PR bumps up the Private SDK version to bring in FH Delete Delta spec changes (some additional fields). 
Also, I have refactored the logging kafka listener aspect to use the MessageHeaders object instead of getting headers from an array using index numbers. With this, I also copied across the test for this aspect from ACSP Delta Consumer.
[DSND-3122](https://companieshouse.atlassian.net/browse/DSND-3122)
[DSND-3122]: https://companieshouse.atlassian.net/browse/DSND-3122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3122: Bump private sdk version

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
* Unset scale in cooldown which is the length of time to wait before reducing the number of running tasks.
* Increase scale out cooldown which is the length of time to wait before increasing the number of running tasks.
* This prevents autoscaling from kicking in during service deployment which can cause the service to reach an unhealthy state.
[See link for info](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html#:~:text=Amazon%20ECS%20publishes,of%20low%20utilization.)
[Jira Ticket](URL)
=> Correct scaling cooldown config to delay scale out instead of scale in

Makefile, README.md, pom.xml, src/main/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClient.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteApiClientRequest.java, src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaService.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/apiclient/FilingHistoryApiClientTest.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/AbstractKafkaIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerInvalidPayloadExceptionIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerNonRetryableExceptionIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerRetryableExceptionIT.java, src/test/java/uk/gov/companieshouse/filinghistory/consumer/service/DeleteDeltaServiceTest.java
This PR adds the parent entity id to the request headers to to FH Data API's delete endpoint.
[DSND-3241](https://companieshouse.atlassian.net/browse/DSND-3241)
[DSND-3241]: https://companieshouse.atlassian.net/browse/DSND-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3241: Add parent entity id to delete request headers

src/main/resources/transform_rules.yml, src/test/java/uk/gov/companieshouse/filinghistory/consumer/kafka/ConsumerPositiveComprehensiveIT.java, src/test/resources/data/persons-with-significant-control/PSC01_date_no_name_delta.json, src/test/resources/data/persons-with-significant-control/PSC01_date_no_name_request_body.json, src/test/resources/data/persons-with-significant-control/PSC01_name_and_date_delta.json, src/test/resources/data/persons-with-significant-control/PSC01_name_and_date_request_body.json, src/test/resources/data/persons-with-significant-control/PSC01_name_no_date_delta.json, src/test/resources/data/persons-with-significant-control/PSC01_name_no_date_request_body.json, src/test/resources/data/persons-with-significant-control/PSC01_no_name_no_date_delta.json, src/test/resources/data/persons-with-significant-control/PSC01_no_name_no_date_request_body.json
* Changes transorm_rules.yml to allow PSC01 transactions to have a mix of field variations: 
* both name and date
* with name but without date
* with date but without name
* neither name nor date
[BI-14445](https://companieshouse.atlassian.net/browse/BI-14445)
[BI-14445]: https://companieshouse.atlassian.net/browse/BI-14445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-14445: Amend PSC01 rules to allow missing fields
